version: '2'
services:
    jobseeker-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/jobseeker/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jobseeker
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
